name: Generate latest.json

on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Install trunk
        run: cargo install trunk

      - name: Build Tauri App (Windows MSI)
        run: cargo tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      - name: Upload MSI artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: target/release/bundle/msi/*.msi

      - name: Debug Build Artifacts
        shell: pwsh
        run: |
          Write-Host "=== Built files under target/release/bundle ==="
          Get-ChildItem -Recurse -Path target/release/bundle | ForEach-Object { $_.FullName }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            target/release/bundle/msi/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create latest.json
        shell: bash
        run: |
          MSI=$(ls target/release/bundle/msi/*.msi | head -n 1)
          SIG=$(cat "$MSI.sig")
          cat > latest.json <<EOF
          {
            "version": "${{ github.ref_name }}",
            "notes": "Automated release",
            "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "platforms": {
              "windows-x86_64": {
                "signature": "$SIG",
                "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/$(basename $MSI)"
              }
            }
          }
          EOF

      - name: Upload latest.json
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
